### ISSUE TITLE
17px difference in the viewport in Mozilla

### ISSUE THREAD

**Issue by jazz009** [ryanve/response.js#17]
Hi, 
First off all thank you so much for this amazing work. It helps a lot improving my mobile first approach.

I noticed that in Mozilla Firefox, there is a 17px difference between the viewport of a page using response.js  and the "real" viewport.

For example if I open the test page (http://responsejs.com/test/) in Mozilla using the adaptive mode (Ctrl + maj + m) and i choose 800 x1280 in the drop down list i will have R.viewportW()    783

After testing a website i'm working on, i found again this 17px difference  in the viewport.
I call an image to replace the default text at 641px but the change take place at 658px

The same thing append in IE9, but not in Chrome.

Did you ever noticed something like that, or am I missing something ?

Thank you again for your time

**Comment by fvpDev** [comment]
Um, just a thought: isn't the 17px difference because of the scrollbar? The difference between browsers is probably due to the different ways the scrollbar is rendered and whether it is considered part of the viewport or not, neh?
