### ISSUE TITLE
Device orientation change

### ISSUE THREAD

**Issue by niallobrien** [ryanve/response.js#52]
Hi all, I'm currently using Response.js in conjunction with Backstretch.js. Upon device orientation change it seems that my Backstretch code isn't being re-called and I had to add something like the following to get it to work:

```
R.action(function() {
  if (R.viewportW() < "640" ) {
    detectOrientation();
      window.onorientationchange = detectOrientation;
      function detectOrientation(){
        if(typeof window.onorientationchange != 'undefined'){
          if ( (orientation >= -90) && ( orientation <= 180) )  {
            $("#selector").backstretch("/images/to-backstretch.jpg");
          }
        }
      }
   }
}
```

Shouldn't this be part of Response.js?

Thanks in advance.

**Comment by niallobrien** [comment]
Thanks for pointing that out @ryanve. Closing the issue for now as it can be resolved using the method I showed above.

**Comment by ryanve** [comment]
cool
