### ISSUE TITLE
Response.js does not work with JQuery 2.1.0 or something else

### ISSUE THREAD

**Issue by dkova** [ryanve/response.js#59]
Dear Author,

Please help me. I have tried an example code:
````html
                <div
                    data-r320='markup @ 320+' 
                    data-r481='markup @ 481+'
                    data-r641='markup @ 641+'
                    data-r961='markup @ 961+' 
                    data-r1025='markup @ 1025+' 
                    data-r1281='markup @ 1281+' 
                >
                optional default markup
                </div>
````
I have JQuery2 connected in header:
````html
   <script type="text/javascript" src="/templates/js/jquery-2.1.1.min.js"></script>
````
And Response.js on footer:
````html
<script type="text/javascript" src="/templates/js/response.min.js"></script>
````
But example code and other  aren't working. My <body>:
````html
<body class="metro" data-responsejs='{
  "create": [
    { "prop":"width", "prefix": "min-width-", "lazy":true }
    , { "prop":"height", "prefix": "min-height-", "lazy":true }
    , { "prop":"device-width", "prefix": "min-device-width-", "lazy":true }
    , { "prop":"device-height", "prefix": "min-device-height-", "lazy":true }
    , { "prop":"device-pixel-ratio", "breakpoints":[0, 1, 1.5, 2] }
  ]}'>
````
Please help to solve this problem.

**Comment by ryanve** [comment]
It looks fine at a glance. It may be an issue with something else on your page. Check your console for errors.

**Comment by dkova** [comment]
There is no errors in Firebug console...

**Comment by dkova** [comment]
It shows "optional markup" phrase

**Comment by ryanve** [comment]
I see the problem. You need to make sure the attribute names match what you specify as the prefix. Attributes like `data-r320` use `"prefix": "r"`. Attributes like `data-min-width-320` use `"prefix": "min-width-"`. If you omit the prefix it will use the default, which happens to be what you have. [See the wiki](https://github.com/ryanve/response.js/wiki/how-to-create-breakpoint-sets#prefixes).

**Comment by dkova** [comment]
Thank you very much!!! It's working!
And I have one more question. How to make like this - if screen is small, style="position:fixed" is disabled?

**Comment by ryanve** [comment]
Use media queries in your CSS

```css
@media (min-width: 481px) {
  .example { position: fixed; }
}
```
