### ISSUE TITLE
Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by davesunny1985** [ryanve/response.js#66]
hi there,

I am getting the following error when calling respons.create function:

Cannot read property 'create' of undefined

Can you please help me with it?

Thanks :)

**Comment by ryanve** [comment]
It's spelled `Response.create` :)

**Comment by davesunny1985** [comment]
I think I can not resolve jquery dependency for response.js
And it ends up catching that warning of aborting response.js

Can you please help me how shall I go about it?

I am basically using webpack for that

![image](https://user-images.githubusercontent.com/18183326/30620984-f24eb578-9deb-11e7-9888-b78b1d55539c.png)


![image](https://user-images.githubusercontent.com/18183326/30620998-139a23fc-9dec-11e7-94c0-9f9094343502.png)
